### ISSUE TITLE
sbt exclusion rules don't handle Scala version specific dependencies

### ISSUE THREAD

**Issue by tlockney** [sbt/sbt#1518]
## steps

``` scala
"net.liftweb" %% "lift-mapper" % "2.6-M4" % "compile" excludeAll(ExclusionRule("net.liftweb", "lift-json"))
```
## problem

`"net.liftweb" %% "lift-json"` is actually not excluded (because you need cross versioned `"lift-json_2.10"`). 
## expectation

`ExclusionRule` could smart up some how, or accept `GroupArtifactID`. The LHS of `excludeAll` is `ModuleID` so it _should_ already know the `crossVersion` mode that its in.
## original report

This came up as an issue recently, referenced in [this Stack Overflow post](http://stackoverflow.com/questions/25179314/why-is-sbt-not-excluding-these-libraries-despite-using-excludes/25185923) from Channing Walton. Basically, the issue is that since exclusion rules are a pretty direct mapping (as I recall, anyway) onto Ivy, they don't include relevant information that sbt knows, such as the Scala version being referenced. So, while you can include a dependency that's Scala specific using the `%%` syntax, there's no similar mapping available for exclusions. I'm not sure what form a solution to this might take, but at least extending it to include something along the lines of the `ModuleID` support for `%%` might make sense, as a start.

**Comment by eed3si9n** [comment]
Thanks for reporting this. I've ran into this myself while trying to use exclusion rules, and it's annoying.

**Comment by eed3si9n** [comment]
`scalaFullVersion` is available during resolution via `IvyScala` instance on `moduleSetting` passed in to create `IvySbt#Module`. Using this we probably could transform the exclusion rules, which feels a bit evil. Maybe it's better to use `GroupArtifactID` ("org" %% "name").

**Comment by mosesn** [comment]
:+1: exclude is very difficult to use against scala jars right now, this would be a significant improvement.

**Comment by dpratt** [comment]
I vote for this as well - it'd be nice to have syntax that would look like

"com.typesafe.play" %% "play-json" % "2.3.6" exclude("com.typesafe.play" %% "play-iteratees")

**Comment by magro** [comment]
+1, for now I'm using a very simple and stupid solution: `exclude("com.typesafe.play", "play_" + scalaVersion.value.substring(0, 4)`

**Comment by reid-spencer** [comment]
+1

**Comment by eed3si9n** [comment]
I did add project-level exclusion that uses ModuleID syntax in #1748

**Comment by stephanh** [comment]
+1 for a version of `exclude` that takes into consideration the scala binary version.

**Comment by LouisJB** [comment]
+1 (+100) - really would be very useful indeed...

**Comment by dnrusakov** [comment]
+1

**Comment by michalstutzmann** [comment]
+1

**Comment by tlockney** [comment]
This actually just bit me again. Might take a look in the near future at adding a fix for this, if time permits.

**Comment by noahlz** [comment]
:+1:

**Comment by mziemba** [comment]
+1

**Comment by pkelly03** [comment]
👍

**Comment by edesdan** [comment]
+1

**Comment by ryan-williams** [comment]
I'm using this workaround:

```scala
"com.holdenkarau" %% "spark-testing-base" % "1.6.3_0.4.7" exclude("org.scalatest", s"scalatest_${scalaBinaryVersion.value}")
```

If anyone has better/cleaner ideas I'd love to hear them!

**Comment by domdorn** [comment]
hmm.. any updates? was affected by this just today.. >2 years since ticket was opened..

**Comment by arpadtamasi** [comment]
Annoying me, too

**Comment by manjuraj** [comment]
+1

**Comment by aakashsa** [comment]
+1

**Comment by jvican** [comment]
Hello everyone and thank you for your patience!
  
The Scala Center has contributed a fix for this here: https://github.com/sbt/librarymanagement/issues/88. It will be merged in 1.0. That PR depends on a big pending PR reformatting all the sources, so don't get scared when you see the diff. The actual fix is [this commit](https://github.com/sbt/librarymanagement/pull/88/commits/c5b7245314f7eb9f1a4c9393dfef27b49715d842) and [these are the tests](https://github.com/sbt/librarymanagement/pull/88/commits/c5b7245314f7eb9f1a4c9393dfef27b49715d842#diff-48f13e7cf9a6707bbd4ede77528e9d62R49) that prove the issue is fixed.

**Comment by tlockney** [comment]
@jvican that's great news! Very much looking forward to seeing this commonly encountered, but tricky to recognize scenario getting resolved. Makes me all the more excited to see 1.0 come to life!

**Comment by samudurand** [comment]
I am still having the issue related to the number of version in the exclusion
This is not excluding : 
```
  val scalaKafkaClient = "net.cakesolutions" %% "scala-kafka-client-akka" % scalaKafkaClientVersion exclude ("com.typesafe.akka", "akka-actor")
```
But this works
``` 
  val scalaKafkaClient = "net.cakesolutions" %% "scala-kafka-client-akka" % scalaKafkaClientVersion exclude ("com.typesafe.akka", "akka-actor_12")
```
I thought from sbt 1.0 I would not need to explicitely set the scala version ?

**Comment by jvican** [comment]
@samudurand 
```scala
val scalaKafkaClient = "net.cakesolutions" %% "scala-kafka-client-akka" % scalaKafkaClientVersion exclude ("com.typesafe.akka" %% "akka-actor")
```

**Comment by samudurand** [comment]
@jvican looks good ! I will try that tonight

**Comment by samudurand** [comment]
@jvican this does work but not with ```exclude``` , instead use ```excludeAll()```

**Comment by otto-dev** [comment]
Temp fix:
```
      libraryDependencies += "com.outworkers" %% "phantom-dsl" % Version.phantom excludeAll (
        ExclusionRule(organization = "org.typelevel"),
      ),
    ),
```

**Comment by mkurz** [comment]
Does this really work with sbt 1.9.7? For me it seems not...

I have a dependency:
```sbt
val atomRenderer = ("com.gu" %% "atom-renderer" % "1.2.0")
```
Now I want to exclude a dependency and it only works when appending `_2.13` to it, everything else fails:
```sbt
.exclude("com.typesafe.play", "twirl-api_2.13") // works

.exclude("com.typesafe.play", "twirl-api") // does NOT work

.excludeAll("com.typesafe.play" %% "twirl-api") // does NOT work
```

**Comment by kirach** [comment]
Same here, `excludeAll("..." %% "...")` does not work for me (sbt version `1.8.2`)
