### ISSUE TITLE
SBT doesn't see new SNAPSHOT dependency versions in local maven repos 

### ISSUE THREAD

**Issue by tomdz** [sbt/sbt#321]
I'm using SBT with a local maven repo cache (e.g. `~/.m2/repository`) for a Scala project that depends on a snapshot version of Java library that I develop at the same time. E.g. I add/change something in the java library and use maven to build a new snapshot version of the library. However, no combination of sbt commands (`update`, `clean`, etc.) will make it see the new snapshot version in the local repo - I have to delete the library from the ivy cache every time. It would be great if sbt/ivy would consider the timestamp of the snapshot version and update accordingly.

**Comment by earldouglas** [comment]
I have a similar issue; possibly a duplicate.  https://github.com/harrah/xsbt/issues/335

**Comment by wpraet** [comment]
Hi, any news on this one? Is it fixed in sbt-0.12.x?

**Comment by absurdhero** [comment]
This does not seem to be a duplicate of 335 since running clean does not work as a workaround.
This behavior also remains even if you set the dependencies that are in your local maven repo as changing().

Reproduction Info:

I added the local maven repo and dependencies to sbt with the following lines in build.sbt:

resolvers += "Local Maven Repository" at Path.userHome.asFile.toURI.toURL + ".m2/repository"

libraryDependencies += "com.example.local" % "localproject" % "1.0-SNAPSHOT" changing()

Running "maven clean install" on localproject installs it to ~/.m2/repository

Code changes are not reflected in my sbt project and the ivy cache located at play/repository/cache/com.example.local/localproject/  (since I am using Play)
contains the old copy of the installed package.

**Comment by snopoke** [comment]
I'm also having the same problem and find it very frustrating having to manually clear out the cache to get ivy to see the changes. I'm still using 0.11.2.

**Comment by jlc** [comment]
Hi everyone,

Does anyone has any news about this issue?

I also have it and the only solution which I could find is to change the version number. As you might guess, this is extremely annoying.
Moreover, I have completely removed the directory ~/.ivy2, unfortunately this didn't have any positive effects.

This is just to know if a fix to this issue is currently in progress.

Thanks for your work!

Jeanluc

**Comment by forceoflight** [comment]
Hello,

this issue is still visible in Play Framework 2.1.0 with sbt version 0.12.2. Has someone from the sbt team studied what could cause this issue?

Regards,
Markku

**Comment by ghost** [comment]
Same issue here with Play2 and sbt

**Comment by David-Noble-at-work** [comment]
Same frustrating issue here with play 2.1.1 and sbt 0.12.2. I hope it gets fixed soon. What are others doing to work around this issue?

**Comment by forceoflight** [comment]
Run "play update" and it will fetch latest packages for the SNAPSHOT
dependencies.

**Comment by admackin** [comment]
I'm getting the same with sbt 0.12.3 still, and `sbt update` does not fix the problem

Here are the relevant lines (I think) from `sbt last` after running update:

<pre>
[info] Resolving org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT ...
[debug] sbt-chain: Checking cache for: dependency: org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT {compile=[default(compile)]}
[debug] don't use cache for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT: changing=true
[debug] don't use cache for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT: changing=true
[debug]         tried /Users/amack/.ivy2/local/org.apache.uima/ConceptMapper/2.3.2-SNAPSHOT/ivys/ivy.xml
[debug]     local: no ivy file found for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT
[debug] don't use cache for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT: changing=true
[debug]     maven-metadata not available: file:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/maven-metadata.xml
[debug]         tried file:///Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.pom
[debug]     Local Maven Repository: found md file for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT
[debug]         => file:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.pom (2.3.2-SNAPSHOT)
[debug]     default-cache: revision in cache (not updated): org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT
[debug]     found org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT in sbt-chain
</pre>

**Comment by jsuereth** [comment]
@admackin Can you find (and post) your ivydata file?

I believe it would be at:

/Users/amack/.ivy2/cache/org.apache.uima/ConceptMapper/ivydata-1.3.properties

**Comment by admackin** [comment]
Here it is. 

This is of course a customised fork of ConceptMapper, slightly different from the version on Maven Central. 

<pre>
wlan-0a1181da:~ amack$ more /Users/amack/.ivy2/cache/org.apache.uima/ConceptMapper/ivydata-2.3.2-SNAPSHOT.properties
#ivy cached data file for org.apache.uima#ConceptMapper;2.3.2-SNAPSHOT
#Mon May 20 18:15:08 EST 2013
artifact\:ivy\#ivy\#xml\#657790531.is-local=false
artifact\:ivy\#ivy\#xml\#657790531.location=file\:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.pom
artifact\:ConceptMapper\#doc\#jar\#-34302492.is-local=false
artifact\:ConceptMapper\#pear\#pear\#1428932066.exists=true
artifact\:ConceptMapper\#doc\#jar\#-34302492.location=file\:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT-javadoc.jar
artifact\:ConceptMapper\#pom.original\#pom\#-1479721675.location=file\:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.pom
resolver=Local Maven Repository
artifact\:ConceptMapper\#pom.original\#pom\#-1479721675.is-local=false
artifact\:ivy\#ivy\#xml\#657790531.exists=true
artifact.resolver=Local Maven Repository
artifact\:ConceptMapper\#doc\#jar\#-34302492.exists=true
artifact\:ConceptMapper\#jar\#jar\#1162682959.is-local=false
artifact\:ConceptMapper\#jar\#jar\#1162682959.location=file\:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.jar
artifact\:ConceptMapper\#jar\#jar\#1162682959.exists=true
artifact\:ConceptMapper\#pear\#pear\#1428932066.is-local=false
artifact\:ConceptMapper\#pom.original\#pom\#-1479721675.exists=true
artifact\:ConceptMapper\#pear\#pear\#1428932066.location=file\:/Users/amack/.m2/repository/org/apache/uima/ConceptMapper/2.3.2-SNAPSHOT/ConceptMapper-2.3.2-SNAPSHOT.pear
</pre>

**Comment by jodyfanning** [comment]
Same issue. Several java SNAPSHOT dependencies and sbt 12.2 (via play 2.1.0) doesn't see changes to any of them, no matter how you declare the resolvers.

**Comment by thedebugger** [comment]
Struggling with same issue over 6 months now. Let me know if need any information for debugging.

**Comment by felipegs** [comment]
I have the same problem here..Is there no workaround that not involve deleting the cache?

**Comment by toddobryan** [comment]
I'm having the same problem, but my SNAPSHOT is being published to the Ivy local repo, not the Maven one.

I was able to fix the problem by deleting just the project in question from the Ivy cache. It's a pain, but less of a pain than deleting everything and having to re-download. In other words, run something like

```
$ rm -r ~/.ivy2/cache/group.id/artifact.id_version
```

and see if that convinces sbt to use the local version.

**Comment by bpfoster** [comment]
+1

**Comment by yeonhoyoon** [comment]
having the same problem here. currently I'm using a script to delete the ivy cache before build.

**Comment by hsl43** [comment]
i'm having the same problem.  my only workaround is to bump-up the version number of my library project, or do a brute-force delete of the artifact from the play repo cache.

Play 2.1.0
sbt 0.12.2

has anyone given/received an "official" update of the problem?  where does this stand with respects to being patched?

**Comment by jlc** [comment]
Hi,

I still have this issue too, and forced to use the same workaround as @hsl43:
- either bump up the version number of the library which is deployed in the maven repository,
- or delete the local copy in the ivy cache (either in the play/repository/cache directory, or ~/.ivy/cache)

sbt 0.12.3 (and play 2.2.0-M1).

Can we help to resolve it? Do you need extra information?

**Comment by dpratt** [comment]
+1 

This issue has caused my team to abandon the usage of Play and SBT. We have a large internal ecosystem of maven-built libraries, and our engineers cannot work on both a maven-based project and a play application at the same time.

**Comment by greenrd** [comment]
@harrah @jsuereth Are you watching this thread? See complaints above.

**Comment by khellang** [comment]
+1

**Comment by jlc** [comment]
It is true that this issue is opened since 2 years and no one seem to care.

SBT based project (such as Play) loose their attraction to develop with if we cannot import libraries coming from the maven world. This is especially true for large project since maven is still the standard. (cf. @dpratt 's comment).

Currently, as we are using Play, the _only_ solution available is to erase the cache in Play20/repository/cache/groupName as soon as one jar has been updated by maven.

Please @jsuereth @harrah, can we find a way to address it?

**Comment by jsuereth** [comment]
This Is actually a fundamental issue between ivy and maven.  The primary
issue is that a maven local cachr isn't really a maven repository (at least
the variants that ivy expect do not hold true), so adding the maven local
repo for resolution is an easy way to corrupt the ivy cache.

Besides ousting ivy (something we've been seriously considering), I'm not
sure there's an alternative solution we can deliver faster.  Ideas/pull
requests welcome!

**Comment by absurdhero** [comment]
Is there a corresponding ivy ticket that the ivy team uses to track this problem?

Ivy's issue tracker is at https://issues.apache.org/jira/browse/IVY . IVY-1221 looks like one piece of the puzzle but may only address a more specific issue of handling SNAPSHOT versions with different classifiers or file extensions.

**Comment by felipegs** [comment]
Are there any way to not cache the dependency?

**Comment by dpratt** [comment]
@jsuereth - without transforming this thread into a (very unpleasant and irrelevant) Ivy/Maven religious war, how serious are you guys about switching to Aether instead of Ivy? I know that moving would cause things to be drastically simpler for both myself and likely for a lot of the folks building things like IDE integration (for example).

**Comment by jsuereth** [comment]
@dpratt I'd say we're very very serious about getting rid of Ivy.   There's more than one option on the table.  At this point, we're not positive of the final solution.  There are a few "requirements" on the table we want to make sure are met by whatever we move to.  Seamless integration with maven is but one of them.  THe other is seamless integration with our existing ecosystem, which is lacking in Aether right now (We'd have to customize it heavily to handle the current sbt plugin publishing situation).  In addition, we're concerned with what Adept has labelled 'variants' on artifacts.

Whatever we do will need to solve users needs, and we'll have to decide soon.  Once we figure out which basket to throw our 'variant' needs at, you'll see some quick developments.

For now, any interim solution proposed and delivered from the community is highly welcome.  If I had any good ideas that didn't lead to intense pain for the user, I'd try them out myself.

**Comment by jsuereth** [comment]
@felipegs AFAIK no.  Ivy first downloads artifacts into its cache, then exposes the files for sbt to use.   A lot of work sbt has done with Ivy has been around improving the cache via turning off features or tweaking settings to try to keep it stable.

**Comment by frant-hartm** [comment]
As a workaround for this bug I am using play2-maven-plugin (http://nanoko-project.github.io/maven-play2-plugin/maven/release/). It works nicely with Intellij IDEA and I don't need to run play idea everytime there is a change. Also simplifies things when running on jenkins.

**Comment by khellang** [comment]
Awesome job, @harrah! :smile: Is there anything that needs to be done in regards to our resolvers for this workaround to take effect?

**Comment by harrah** [comment]
@khellang This workaround will be enabled by default in 0.13.1 for all Maven repositories that have a base URL with the file protocol (basically, all local Maven repositories).

**Comment by khellang** [comment]
This still isn't working in 0.13.1-RC2 :cry: Anything I can do to help?

**Comment by harrah** [comment]
If it isn't working for you, we'd need a test case.

**Comment by mpilquist** [comment]
Just got a similar issue with 0.13.5-RC1 FYI, but with a twist -- SBT wasn't seeing the new SNAPSHOTs published to local ivy repository via publish-local. The build does have the local maven repository added as a resolver.

**Comment by eed3si9n** [comment]
Could you create a repro case?
If not, you can use [sbt/sbt/sbt-dirty-money](https://github.com/sbt/sbt-dirty-money) to selectively wipe out the Ivy cache.

**Comment by mpilquist** [comment]
If I succeed in repro case, I'll send. At the very least, I should be able to provide access to internal repos via Typesafe support.

**Comment by jasonchaffee** [comment]
I am seeing the same issue with publishing SNAPSHOT's TO publishLocal in 0.13.5.  The cache had a SNAPSHOT version it downloaded from our internal proxy that was published maven style and that was taking precedence over anything built with publishLocal.  It is almost as if they aren't being considered as the same artifact.

**Comment by reid-spencer** [comment]
I think I'm still seeing this issue. I have a local copy of ReactiveMongo and I just built it from scratch and did "publishLocal". Other projects don't find it even if I rebuild them from scratch (i.e. blow away target directory). This issue is closed, but apparently stlll relevant. I'm using 0.13.6

**Comment by jpsacha** [comment]
I see the same problem with 0.13.6 and 0.13.7-RC2. Interestingly, a workaround is to build some project with needed SNAPSHOT using 0.13.5, then 0.13.6 and 0.13.7 can find that SNAPSHOT in other projects. Looks like a regression introduced back in 0.13.6.

**Comment by eed3si9n** [comment]
@reid-spencer @jpsacha Are you both talking about `publishLocal`  or local maven repo cache (e.g. `~/.m2/repository`), which this issue is about?
If it's about publishLocal, it could be a whole another issue, so could you open a new issue, please?

**Comment by jpsacha** [comment]
In my case I publish SNAPSHOT using Maven: "mvn install", then trying to access that SNAPSHOT artifact from SBT build. This seems to me the same as the original description by tomdz from 6/2/12. Comment from 6/3/14 by  jasonchaffee mentions `publishLocal`, though that looks like a bit different scenario.

**Comment by reid-spencer** [comment]
@eed3si9n - For me it is about publishLocal. I don't use or have a maven2 repository. If this starts causing problems again, I will open a new issue.

**Comment by dshefchik** [comment]
I'd just like to add that I found a pretty good workaround for this issue. 

If you prepend instead of append your local Maven repo to the SBT resolver sequence, SBT will resolve updated dependencies from there first. It might not work for you but I'm happy in the meantime. 

Here's my build.sbt: 

```
resolvers := ("Local Maven Repository" at "file:///" + Path.userHome.absolutePath + "/.m2/repository") +: resolvers.value 

  resolvers ++= Seq(
        "pk11 repo" at "http://pk11-scratch.googlecode.com/svn/trunk",
        "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
    )
```

**Comment by jsuereth** [comment]
Yeah, Ivy/sbt generally uses the resolver-order to determine what dependencies to use.  This is different (slightly) from how people expect maven to work, and it wasn't (previously) safe for us to directly use the local maven cache as a remote repo.   Now, we should be able to.

**Comment by dwijnand** [comment]
Josh do you mean as of Aether being used or some other change?

**Comment by jsuereth** [comment]
No.   We actually added hooks to ignore resolver order and check "last modified" times in metadata recently as a workaround.  Before, ivy would take the first resolver that found an artifact, which for sbt was its local cache IIRC.

**Comment by machaval** [comment]
It still can not resolve snapshot dependencies with timestamp https://issues.apache.org/jira/browse/IVY-1476 . Any workarround?

**Comment by oleg-gr** [comment]
What's the current status for this issue? Having problems with sbt 0.13.8 and Resolver.mavenLocal not seeing new SNAPSHOT versions that are being `mvn install`ed into local maven repo. `clean` or `update` don't work

Edit: Sorry, separate issue. Looks like Resolver.mavenLocal doesn't work. Had to manually add `"Local Maven Repository" at "file:///" + Path.userHome.absolutePath + "/.m2/repository"` to resolvers for it to work.

**Comment by libratiger** [comment]
@oleg-gr I have a same issue.  I used the sbt 0.13.7.  Some times ago, I use the `mvn install` publish a local jar in the .m2/repository, and add the resolver like you mentioned `"Local Maven Repository" at "file:///" + Path.userHome.absolutePath + "/.m2/repository"`, it does work. 

But I change my maven project recently, and use the `mvn insall` to publish again, then I update the sbt project, it can not find my jar file now, even I add the `Resolver.mavenLocal`, it does not work. 

so is there any other changed for your project? or like delete the .ivy cache by manually?

**Comment by oleg-gr** [comment]
@djvulee nothing changed for my project. It kind of works. Getting SNAPSHOTs takes forever (since all the repositories need to be checked for all (!!) submodules), especially since for each locally-installed version I get `Server access Error: Operation timed out url=http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/...` and `Server access Error: Operation timed out url=http://repo1.maven.org/maven2/...` which takes a really really long time. Not sure how to fix. Please share if you know the solution

**Comment by libratiger** [comment]
@oleg-gr  Thanks, I also get `Server access Error` for my locally-installed package, I think sbt should resolve the local repository first, and then resolve from remote, but it seems not ,this is very strange.

I will share my experience If I find how to deal with this.

**Comment by oleg-gr** [comment]
Thank you @djvulee. It definitely shouldn't wait for a timeout since it's taking impossibly long. Will let you know if I come up with something

**Comment by gavioto** [comment]
Recently reocmpiling a play 2.4.3 application using sbt 0.13.9 detected new
snapshots on my remote repo.

On 26 November 2015 at 08:22, Oleg notifications@github.com wrote:

> Thank you @djvulee https://github.com/djvulee. It definitely shouldn't
> wait for a timeout since it's taking impossibly long. Will let you know if
> I come up with something
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/321#issuecomment-159834131.

## 

Alberto

**Comment by eed3si9n** [comment]
If sbt 0.13.9 fixes things it might be because of [Maven compatibility fix](http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Maven+compatibility+fix) that got in sbt/ivy#13 / #2075.

**Comment by jmoodymarchex** [comment]
Has a similar issue cropped up again? Since sbt switched to using Coursier, my team has been having issues with dependencies not being updated to the latest version from our private maven repo. Running "sbt update" no longer consistently pulls new versions of dependencies marked with "latest.version" or a maven style range expression. Please help.

**Comment by OldManLink** [comment]
Still not working in `sbt 1.3.8` so I'm following this in case anyone decides to reopen it

**Comment by eed3si9n** [comment]
Please see https://get-coursier.io/docs/ttl and https://github.com/sbt/sbt/issues/5377 if you're hitting it with sbt 1.3.x and above.
