### ISSUE TITLE
1.0.{0,1,2} Opening console multiple times breaks escaping

### ISSUE THREAD

**Issue by clhodapp** [sbt/sbt#3482]
## steps
1. Start an sbt shell
2. Type `console<enter>`
3. Type `ctrl-d` or `:q<enter>`
4. Type `console<enter>`
5. Type an arrow key or `ctrl-n`, `ctrl-p`, `ctrl-r`, etc.

## problem
Escapes are not interpreted correctly and sbt prints out garbage characters.

## expectation
Escapes are interpreted correctly and sbt does not print out garbage characters.

## notes
* I'm on a Mac using iterm 2.
* Bug doesn't exist on sbt 0.13.16

sbt version: *1.0.0*, *1.0.1*

**Comment by hntd187** [comment]
I experience something similar to this in which if I use any sbt command on the terminal my terminal output is completely broken after. I can no longer see any text output at all, but my terminal responds to commands. I have to `reset` the terminal in order to make it work again.

This also effects me on both 1.0.0 and 1.0.1

**Comment by hag0r** [comment]
I experience the same issue as @hntd187 on Fedora 26 (Bash 4.4.12). After executing any sbt command (`sbt clean` or even `sbt sbtVersion`) I don't see any output and have to `reset`.

For projects configured via build.properties to use 0.13.9 everything is fine.

**Comment by clhodapp** [comment]
@hntd187 @sthagedorn I think you guys should be aware of https://github.com/sbt/sbt/issues/3453, which catalogs your specific issue. It's not unlikely that it's related to this, though.

**Comment by clhodapp** [comment]
Note: This was *not* fixed by https://github.com/sbt/sbt/pull/3507 in 1.0.2, as I had been hoping might happen.

**Comment by dwijnand** [comment]
I'll try and find time to have a look for 1.0.3.

**Comment by clhodapp** [comment]
Seems to be fixed in 1.1.0-RC2! I'll close this post-1.1.0 if it remains fixed.

**Comment by dwijnand** [comment]
I strongly suspect this was fixed with #3507, which shipped in sbt 1.0.2!

**Comment by dwijnand** [comment]
Note that #3661 is still impacting `console`. I've added it to the next hotfix milestone, in the hopes we can fix it by then.

**Comment by clhodapp** [comment]
I don't think it was fixed in 1.0.2 but no worries: it does seem to have been fixed at some point. :)

**Comment by laughedelic** [comment]
I still experience it in sbt 1.1.0. It's not #3661, because I can reproduce it with
* opening `console` more than 1 time
* or running `clean`, `compile` and then opening `console` (the first time in this session)

**Comment by jrudolph** [comment]
Yep, same here. If you open and close a console more than once, it's broken the second time.

**Comment by clhodapp** [comment]
I haven't used sbt 1.X for a few months for other reasons but I've just come back to it and am once again seeing this issue (with 1.1.0). Running `jline.TerminalFactory.get.init`, as mentioned by @retronym in https://github.com/sbt/sbt/issues/3661 gets it working again, so at least I seem to have a workaround now.

Can this get re-opened?

**Comment by fommil** [comment]
1.1.2 is out

**Comment by clhodapp** [comment]
Oh whoa! So it is! https://www.scala-sbt.org/download.html is a bit behind then (and I myself missed the big 1.1.1 link in the button, and instead just looked at the list below).

This problem still exists in 1.1.2, though.

**Comment by eed3si9n** [comment]
Confirmed on 1.1.2.

**Comment by dwijnand** [comment]
fixed in #4054 (which will be in sbt 1.1.3)

**Comment by eed3si9n** [comment]
### sbt 1.1.3 + Scala 2.12.4

Testing with

```
$ cat project/build.properties
sbt.version=1.1.3
$ cat build.sbt
lazy val root = (project in file("."))
  .settings(
    ThisBuild / scalaVersion := "2.12.4",
    name := "console test",
  )
$ sbt -Dsbt.global.base=/tmp/sbt_global -Dsbt.ivy.home=/tmp/sbt_ivy
sbt:console test> console
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala>
```

Nothing I type into REPL shows up on the terminal.

### sbt 1.1.3 + Scala 2.12.5

`console` displays normally. I can run `console` twice and JLine still works.

### sbt 1.1.3 + Scala 2.12.3

`console` displays normally. I can run `console` twice and JLine still works.

### sbt 1.1.4 + Scala 2.12.4

`console` displays normally. I can run `console` twice and JLine still works.

### sbt 1.1.4 + Scala 2.12.5

`console` displays normally. But running `console` twice disables JLine. (This bug)

### sbt 1.1.4 + Scala 2.12.3

`console` displays normally. But running `console` twice disables JLine. (This bug)
