### ISSUE TITLE
SBT > 1.0 NullPointerException in JavaNetAuthenticator

### ISSUE THREAD

**Issue by ryanb93** [sbt/sbt#3519]
## steps

Populating ~/.sbt/repositories file with

```
[repositories]
  local
  artifactory-libs-release: http://example.com/artifactory/libs-release
  artifactory-libs-snapshot: http://example.com/artifactory/libs-snapshot
  artifactory-plugin-release: http://example.com/artifactory/plugin-release
  artifactory-plugin-snapshot: http://example.com/artifactory/plugin-snapshot
  artifactory-libs-release-ivy: http://example.com/artifactory/libs-release , [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
```

Populating ~/.sbt/0.13/plugins/credentials.sbt and ~/.sbt/1.0/plugins/credentials.sbt with:

`credentials += Credentials(Path.userHome / ".sbt" / ".credentials")
`

Exporting

```
export SBT_OPTS=-Dsbt.override.build.repos=true
export SBT_CREDENTIALS=$HOME/.sbt/.credentials
```

Running

`sbt clean test +publish`

On a project with

```
  scalaVersion := "2.11.11",
  crossScalaVersions := Seq("2.11.11", "2.12.3")
```

build.properties

`sbt.version=1.0.1`

## problem

The build fails with the following message:

`build	12-Sep-2017 11:43:14	[0m[[0m[31merror[0m] [0m[0munresolved dependency: io.netty#netty;3.7.0.Final: java.lang.NullPointerException at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)[0m`

The project also relies on a plugin that has been cross-built to 0.13.16 and 1.0.0

## expectation

The build to pass. Changing the sbt.version in build.properties to 0.13.16 works fine.

## notes

sbt version: 1.0 and 1.0.1

**Comment by eed3si9n** [comment]
Thanks for the report.

Could you try the following as a workaround please:

```scala
updateOptions := updateOptions.value.withGigahorse(false)
```

**Comment by eed3si9n** [comment]
Does it print out the stack trace? If so it might be helpful for us to pin point where it's failing.

**Comment by DieBauer** [comment]
I've ran into the same issue (also cross building, with custom repositories file, so basically same setup) with sbt 1.0.2 (sbt 0.13.15 was working fine), and disabling gigahorse works for me. (`updateOptions := updateOptions.value.withGigahorse(false)`)

Here is a stack trace when gigahorse was enabled:

```
[error] java.lang.NullPointerException
[error] 	at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:284)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:152)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
[error] 	at okhttp3.RealCall.execute(RealCall.java:69)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:48)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.getURLInfo(GigahorseUrlHandler.scala:29)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.getURLInfo(URLHandlerDispatcher.java:66)
[error] 	at org.apache.ivy.plugins.repository.url.URLResource.init(URLResource.java:65)
[error] 	at org.apache.ivy.plugins.repository.url.URLResource.exists(URLResource.java:81)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:74)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:492)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:491)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:491)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:141)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:154)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:148)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:141)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:131)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:90)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:131)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2217)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2215)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (myProject/*:publish) java.lang.NullPointerException

**Comment by dwijnand** [comment]
This is the NPE that @cunei mentioned in https://github.com/sbt/sbt-contrib/blame/d5eff08929050196633d9203919a937aea006e5d/src/main/markdown/2017-08-16.md#L85.

**Comment by LogicalTime** [comment]
Using keystore style authentication (adding -Djavax.net.ssl.trustStore type params to SBT_OPTS) also seems to fail for SBT 1.0.2 (ssl handshake issues). Switching project back to 0.13.15 allows https connections to repositiories again. Just mentioning it in case the authentication issues are related. I'll see if:
updateOptions := updateOptions.value.withGigahorse(false)

helps tomorrow.

**Comment by StephenWithPH** [comment]
My situation is identical to @DieBauer in https://github.com/sbt/sbt/issues/3519#issuecomment-331395080... resolved in similar fashion.

**Comment by francisdb** [comment]
Also seeing this issue when publishing to Nexus

```scala
publishTo := {
  val nexus = "https://nexus.company.com"
  if (isSnapshot.value)
    Some("Company snapshot repo" at nexus + "/repository/maven-snapshots")
  else
    Some("Company releases repo" at nexus + "/repository/maven-releases")
}
```

only the pom (and hashes) were uploaded correctly.
(disabling gigahorse indeed fixes this)

**Comment by note** [comment]
I found that issue because the top line of my stacktrace is the same and I got the issue after I bumped sbt from 0.13.x to 1.0.2. But issue I am experiencing is not triggered by publishing. My build depends on library hosted on private bintray repository and after sbt version bump the build fails randomly - interestingly only on CI, I was not able to replicate it locally (tried everything like wiping out ivy cache). Bintray also seemed to be more or less stable that time (was curling the URL sbt was complaining about).

The workaround proposed in that ticket seemed to worked.

I am attaching my stacktrace for your investigation:

```
warn]  Note: Unresolved dependencies path:
[warn]          com.example:my-lib_2.12:0.1.+ (/app/build.sbt#L42)
[warn]            +- my-lib:my-lib_2.12:0.0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.example#my-lib_2.12;0.1.+: java.lang.NullPointerException at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by dwijnand** [comment]
https://github.com/sbt/librarymanagement/pull/177 wasn't merged, so this wasn't fixed by bumping lm.

**Comment by LogicalTime** [comment]
The compiler-bridge dependency doesn't seem to ship with SBT and I'm not sure how to set 
updateOptions := updateOptions.value.withGigahorse(false)
Before that SBT dependency is asked for. So it is tricky to get off the ground with SBT 1.x. I'm not sure if putting the updateOptions line in the global plugins.sbt would do the trick. Is there a sbtopts flag one could use?

**Comment by levinson** [comment]
The posted workaround does not work for me in SBT 1.0+ (tested 1.1.0 and 1.1.1).
EDIT: I encountered this issue in a simple Scala.js cross-compiled library. It worked fine when I rolled back sbt to 0.13.17. If it's helpful I could put together a minimal example project.

**Comment by reid-spencer** [comment]
:+1:  - Using 1.1.1, with `updateOptions := updateOptions.value.withGigahorse(false)` and have the same exception occuring on initial update for one artifact during download from Nexus repository.

**Comment by amogh09** [comment]
Any updates on this? Disabling gigaHorse helps on OS X but not on Ubuntu.

**Comment by amogh09** [comment]
I struggled with `updateOptions := updateOptions.value.withGigahorse(false)` a bit. 

When on a fresh container with a freshly cloned project, running `sbt test` as the first command gives NPE while resolving plugins. But if I run `sbt compile` before running `sbt test` then there is no NPE. 

Seems like the setting line is not reached before plugins are loaded in case of `sbt test` for my project.

**Comment by LogicalTime** [comment]
There is an SBT opts flag you can pass in to do updateOptions := updateOptions.value.withGigahorse(false). That had solved all my issues. I forget the name though.

**Comment by leoRoss** [comment]
The flag mentioned above is `-Dsbt.gigahorse=false`.
`sbt compile publish -Dsbt.gigahorse=false`

Using this flag fixed our issues

**Comment by komsit37** [comment]
Just want to add some info that could be useful:
1. Still got the same error in sbt 1.1.5 (java.lang.NullPointerException at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)  when doing `sbt publish` 
2. I have a multi-module projects with a custom publish task in root project. Properly disable publish in a non-publishing module fixes this issue for me.

for example i have a project with 3 modules: module-a, module-b, module-c all aggregate under root-module.
```
//custom publish task in root-module
publish := {
  (publish in Universal in `module-a`).value
  (publish in `module-b`).value
}
//...
//`module-c` setting
publish := {}
```

I haven't tried `updateOptions := updateOptions.value.withGigahorse(false)`, but this workaround works for me.

**Comment by francisdb** [comment]
Pretty crazy that this has not been fixed yet after more than a half year, anything we can do to get this going?

**Comment by eed3si9n** [comment]
I opened a pull request last year based on the stack trace on this issue - https://github.com/sbt/librarymanagement/pull/177
I think the problem was that it never got merged because we weren't able to reproduce the issue in the test environment.

**Comment by gabriel-bezerra** [comment]
Does the Merged Upstream label mean it is about to be fixed in the next version of sbt?

**Comment by eed3si9n** [comment]
@gabriel-bezerra Yes

**Comment by gabriel-bezerra** [comment]
Thanks, Eugene.

**Comment by dwijnand** [comment]
Updated the label description to communicate this going forward (https://github.com/sbt/sbt/labels).

**Comment by GaalDornick** [comment]
I still get this error on v1.2.1. 
1) Clean out my ivy cache
2) Clone https://github.com/apache/incubator-toree 
3) Run make release

I get

```[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.fasterxml.jackson.core#jackson-databind;2.6.5: Resolution failed several times for dependency: com.fasterxml.jackson.core#jackson-databind;2.6.5 {test=[default(compile)]}:: 
[error] 	Resolution failed several times for dependency: com.fasterxml.jackson#jackson-parent;2.6.2 {}:: 
[error] 	Resolution failed several times for dependency: com.fasterxml#oss-parent;24 {}:: 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
```

when I turn on debug, I see this

```
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried /Users/gxc772/.ivy2/local/com.fasterxml/oss-parent/24/jars/oss-parent.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried https://repo1.maven.org/maven2/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0mCLIENT ERROR: Not Found url=https://repo1.maven.org/maven2/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried http://repository.apache.org/snapshots/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0mproblem occurred while resolving dependency: com.fasterxml#oss-parent;24 {} with public: java.lang.NullPointerException^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m  at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)^[[0m
```
SBT is tried to download the jar for a POM type module. Obviously, POM modules don't have jars, so it tries every repository until the last one and gives this exception

**Comment by eed3si9n** [comment]
This looks like a different stack trace, so I am going to use the new GitHub feature and open a new issue.
