### ISSUE TITLE
"CreateFile() failed with error 32" from IO.getModifiedTimeOrZero on Windows

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3972]
(split from @jccode's comment in https://github.com/sbt/sbt/issues/3871#issuecomment-368207530)

> I face a similar issue on Windows7,  sbt version is 1.1.1.  
> Here are the error messages. 
> 
>      all {file:/E:/jc/code/scala-train/}scala-train/products {file:/E:/jc/code/scala-train/}scala-train/test:products
>     [error] java.io.IOException: CreateFile() failed with error 32
>     [error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:290)
>     [error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:296)
>     [error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:274)
>     [error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:67)
>     [error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:376)
>     [error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
>     [error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
>     [error]         at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:150)
>     [error]         at sbt.util.FileInfo$lastModified$.apply(FileInfo.scala:125)
>     [error]         at sbt.Sync$.$anonfun$apply$2(Sync.scala:40)
>     [error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
>     [error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
>     [error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
>     [error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
>     [error]         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:178)
>     [error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
>     [error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
>     [error]         at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
>     [error]         at scala.collection.SetLike.map(SetLike.scala:101)
>     [error]         at scala.collection.SetLike.map$(SetLike.scala:101)
>     [error]         at scala.collection.AbstractSet.map(Set.scala:47)
>     [error]         at sbt.Sync$.$anonfun$apply$1(Sync.scala:40)
>     [error]         at sbt.Defaults$.$anonfun$copyResourcesTask$1(Defaults.scala:1538)
>     [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
>     [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
>     [error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
>     [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
>     [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
>     [error]         at sbt.Execute.work(Execute.scala:271)
>     [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
>     [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
>     [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
>     [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     [error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     [error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     [error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     [error]         at java.lang.Thread.run(Thread.java:745)
>     [IJ]sbt:scala-train>
>     [error] (Compile / copyResources) java.io.IOException: CreateFile() failed with error 32
>     [error] Total time: 1 s, completed 2018-2-24 15:06:26
>     [IJ]sbt:scala-train>
> 
> The workaround `-Dsbt.io.jdktimestamps=true` can fix this issue temporarily.
> Let me know if I need to provide more useful information. 

@jccode could you see if you can add some more details, following our issue template, please? https://github.com/sbt/sbt/blob/v1.1.1/ISSUE_TEMPLATE.md

**Comment by dwijnand** [comment]
if I'm understanding correctly (I've no idea, really) "error 32" is ERROR_SHARING_VIOLATION: "The process cannot access the file because it is being used by another process.". From https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx.

**Comment by cunei** [comment]
I think I have an idea about this issue, I created a pull request and will run some tests.

**Comment by dwijnand** [comment]
thanks Toni

**Comment by cunei** [comment]
Hello @jccode, I have prepared a patched version that you can test. To verify the patch, please add to your list of resolvers the following: `https://dl.bintray.com/sbt/maven-snapshots`, as described at https://github.com/sbt/sbt/issues/3871, and use this sbt version: `1.1.2-bin-20180226T135405`. Kindly let us know if it works correctly with your code.

**Comment by jccode** [comment]
Sorry for the late response. @cunei I test the patched version, which give me the follow errors. 

    [info] Running ch_ltd.Init
    [error] (run-main-0) java.nio.charset.MalformedInputException: Input length = 1
    [error] java.nio.charset.MalformedInputException: Input length = 1
    [error]         at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
    [error]         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
    [error]         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    [error]         at java.io.InputStreamReader.read(InputStreamReader.java:184)
    [error]         at java.io.BufferedReader.fill(BufferedReader.java:161)
    [error]         at java.io.BufferedReader.readLine(BufferedReader.java:324)
    [error]         at java.io.BufferedReader.readLine(BufferedReader.java:389)
    [error]         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:70)
    [error]         at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:447)
    [error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
    [error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
    [error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
    [error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
    [error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
    [error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
    [error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
    [error]         at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
    [error]         at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
    [error]         at scala.collection.AbstractIterator.to(Iterator.scala:1417)
    [error]         at scala.collection.TraversableOnce.toList(TraversableOnce.scala:294)
    [error]         at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:294)
    [error]         at scala.collection.AbstractIterator.toList(Iterator.scala:1417)
    [error]         at ch_ltd.Init$.loadRecordsFromFile(Init.scala:10)
    [error]         at ch_ltd.Init$.main(Init.scala:21)
    [error]         at ch_ltd.Init.main(Init.scala)
    [error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [error]         at java.lang.reflect.Method.invoke(Method.java:497)
    [error]         at sbt.Run.invokeMain(Run.scala:93)
    [error]         at sbt.Run.run0(Run.scala:87)
    [error]         at sbt.Run.execute$1(Run.scala:65)
    [error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
    [error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    [error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
    [error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
    [error]         at java.lang.Thread.run(Thread.java:745)
    [error] java.lang.RuntimeException: Nonzero exit code: 1
    [error]         at sbt.Run$.executeTrapExit(Run.scala:124)
    [error]         at sbt.Run.run(Run.scala:77)
    [error]         at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1169)
    [error]         at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1164)
    [error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
    [error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    [error]         at scala.util.Try$.apply(Try.scala:209)
    [error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
    [error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [error]         at java.lang.Thread.run(Thread.java:745)
    sbt:scala-train> [error] (Compile / run) Nonzero exit code: 1
    [error] Total time: 4 s, completed 2018-3-1 9:49:27

**Comment by jccode** [comment]
Last time I encounter this issue (error 32) both on sbt running on CMD and IntelijIDEA.
However, I try to reproduce the issue this morning, I can only reproduce it on sbt running on CMD, not in IntelijIDEA(even I use sbt 1.1.1, remove the -Dsbt.io.jdktimestamps=true option). Thus I feel very confused.

**Comment by jccode** [comment]
I describe the test result.

Steps:

1. Use sbt 1.1.1, remove the "-Dsbt.io.jdktimestamps=true" option to reproduce the (error 32) issue.
   a). Running on IntelijIDEA, I cannot reproduct it again.
   b). Running sbt on CMD, I can reproduct the issue.
2. Using sbt 1.1.2-bin-20180226T135405, re-run on CMD again, I encounter another error, but I confirm that's the issue for my business code, not related to sbt. Thus, I think the patched version fix the issue.
3. I change back the sbt version to 1.1.1, hope to reproduce the previous(error 32) issue. But I can not reproduce it anymore.

Strange things.  Is anything I can do next? :(

**Comment by cunei** [comment]
Hello @jccode, it is a bit difficult to establish whether the patch fixed this issue without a self-contained and reproducible test case. In theory it should, but validating the fix is a bit difficult without having an idea of where your issue originates from. If you manage to create a standalone test, that would be ideal; otherwise we will try and run some local tests, and then will evaluate whether to include the patch in the current code base. Thanks for letting us know about this issue, in any case.

**Comment by eed3si9n** [comment]
Another `CreateFile() failed with error` reported here - https://github.com/sbt/website/issues/650

**Comment by cunei** [comment]
@eed3si9n This should be fixed in https://github.com/sbt/io/pull/134, which has been merged in 1.x.

**Comment by ochrons** [comment]
I got the same issue on sbt 1.1.2 when running sbt both from WSL (linux subsystem) and regular Windows. Running multiple sbt instances from Windows alone works ok.

**Comment by dwijnand** [comment]
@ochrons the (hopeful) fix for this will ship in sbt 1.2.0.

You might be able to verify with a nightly build, which I documented yesterday: https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md#using-jenkins-sbt-snapshots-nighties

**Comment by ochrons** [comment]
I tried with the snapshot version (1.2.0-bin-20180423T192044), but the same problem persists. If I start sbt first under WSL and then in Windows I get.
```text
$ sbt -Dsbt.repository.config=repositories
[info] Loading settings from idea.sbt,plugins.sbt ...
[info] Loading global plugins from C:\Users\oc\.sbt\1.0\plugins
[error] java.io.IOException: CreateFile() failed with error 32
[error]         at sbt.internal.io.WinMilli$.getHandle(Milli.scala:290)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:296)
[error]         at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:274)
[error]         at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:67)
[error]         at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:376)
[error]         at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error]         at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error]         at sbt.internal.LibraryManagement$.$anonfun$fileUptodate$1(LibraryManagement.scala:124)
```

This happens even if WSL and Win sbt are started in different projects, so it must be something in the global files that causes the conflict. Also note that WSL and Win have different `.sbt` directories.

If I use sbt 1.0.4 on the project (on Windows side) it doesn't happen, but with 1.1.x it does.

I checked what happens when sbt starts, using the `procmon` tool, and found a SHARING_VIOLATION on `C:\Users\oc\.ivy2\cache\org.scala-lang.modules\scala-xml_2.12\bundles\scala-xml_2.12-1.0.6.jar`. The `.ivy2` folder is shared between WSL and Windows. All other JAR libraries opened fine, though.

![image](https://user-images.githubusercontent.com/629483/39307465-8a499bf6-496b-11e8-945a-c53cd87cde23.png)

**Comment by dwijnand** [comment]
@cunei maybe you're best suited: if you have time, could you look at the above, please?

**Comment by ochrons** [comment]
I did some further investigation and the scala-xml seems to have been triggered partly because of IntelliJ running at the same time. Without IntelliJ the sharing violation occurs with the sbt jar itself.

```text
C:\Users\oc\.ivy2\cache\org.scala-sbt\sbt\jars\sbt-1.2.0-bin-20180423T192044.jar
```
Same with 1.1.4

In WSL I have
```text
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
on Win side I have
```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

EDIT: Same result with the latest jre8-172 version, except now the SHARING VIOLATION is again the scala-xml jar... Weird stuff 😅

**Comment by cunei** [comment]
@ochrons, in the picture the access information is partially outside the frame; would you please be able to take a snapshot of the desired access that is listed, and any other access information that the tool is reporting at that point? Thanks!

**Comment by ochrons** [comment]
All the files that were opened were requested with the same shared read access,

```
Operation:	CreateFile
Result:	SHARING VIOLATION
Path:	C:\Users\oc\.ivy2\cache\org.scala-lang.modules\scala-xml_2.12\bundles\scala-xml_2.12-1.0.6.jar
TID:	17120
Duration:	0.0000128
Desired Access:	Generic Read
Disposition:	Open
Options:	Synchronous IO Non-Alert
Attributes:	n/a
ShareMode:	Read
AllocationSize:	n/a
```

Here's a full dump of all file access that happens in the ivy2 folder before the failure
```
10.11.01,2178276	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\net.virtual-void\sbt-dependency-graph\jars\sbt-dependency-graph-0.9.0.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2179917	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\net.virtual-void\sbt-dependency-graph\jars\sbt-dependency-graph-0.9.0.jar	SUCCESS	CreationTime: 11.11.2017 15.39.47, LastAccessTime: 11.11.2017 15.39.47, LastWriteTime: 24.10.2017 19.21.49, ChangeTime: 11.11.2017 15.39.47, FileAttributes: A
10.11.01,2180584	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\net.virtual-void\sbt-dependency-graph\jars\sbt-dependency-graph-0.9.0.jar	SUCCESS	
10.11.01,2182312	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\com.dwijnand\sbt-compat\jars\sbt-compat-1.1.0.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2183414	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\com.dwijnand\sbt-compat\jars\sbt-compat-1.1.0.jar	SUCCESS	CreationTime: 11.11.2017 15.39.48, LastAccessTime: 11.11.2017 15.39.48, LastWriteTime: 6.10.2017 11.36.52, ChangeTime: 11.11.2017 15.39.49, FileAttributes: A
10.11.01,2183939	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\scala_2.12\sbt_1.0\com.dwijnand\sbt-compat\jars\sbt-compat-1.1.0.jar	SUCCESS	
10.11.01,2185478	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.12.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2186674	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.12.4.jar	SUCCESS	CreationTime: 2.11.2017 14.04.25, LastAccessTime: 2.11.2017 14.04.25, LastWriteTime: 11.10.2017 10.07.10, ChangeTime: 2.11.2017 14.04.28, FileAttributes: A
10.11.01,2187086	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.12.4.jar	SUCCESS	
10.11.01,2188676	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\sbt\jars\sbt-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2190240	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\sbt\jars\sbt-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.34, LastAccessTime: 23.4.2018 22.19.34, LastWriteTime: 9.4.2018 20.52.49, ChangeTime: 23.4.2018 22.19.35, FileAttributes: A
10.11.01,2190671	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\sbt\jars\sbt-1.1.4.jar	SUCCESS	
10.11.01,2192232	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\main_2.12\jars\main_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2193683	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\main_2.12\jars\main_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.35, LastAccessTime: 23.4.2018 22.19.35, LastWriteTime: 9.4.2018 20.53.32, ChangeTime: 23.4.2018 22.19.36, FileAttributes: A
10.11.01,2194226	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\main_2.12\jars\main_2.12-1.1.4.jar	SUCCESS	
10.11.01,2195714	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\logic_2.12\jars\logic_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2196768	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\logic_2.12\jars\logic_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.36, LastAccessTime: 23.4.2018 22.19.36, LastWriteTime: 9.4.2018 20.53.04, ChangeTime: 23.4.2018 22.19.36, FileAttributes: A
10.11.01,2197187	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\logic_2.12\jars\logic_2.12-1.1.4.jar	SUCCESS	
10.11.01,2198712	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\collections_2.12\jars\collections_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2199875	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\collections_2.12\jars\collections_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.37, LastAccessTime: 23.4.2018 22.19.37, LastWriteTime: 9.4.2018 20.52.57, ChangeTime: 23.4.2018 22.19.38, FileAttributes: A
10.11.01,2200298	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\collections_2.12\jars\collections_2.12-1.1.4.jar	SUCCESS	
10.11.01,2201775	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-scalajson_2.12\jars\sjson-new-scalajson_2.12-0.8.2.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2202818	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-scalajson_2.12\jars\sjson-new-scalajson_2.12-0.8.2.jar	SUCCESS	CreationTime: 27.1.2018 12.05.42, LastAccessTime: 27.1.2018 12.05.42, LastWriteTime: 13.12.2017 4.46.42, ChangeTime: 27.1.2018 12.05.42, FileAttributes: A
10.11.01,2203216	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-scalajson_2.12\jars\sjson-new-scalajson_2.12-0.8.2.jar	SUCCESS	
10.11.01,2204805	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-core_2.12\jars\sjson-new-core_2.12-0.8.2.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2205848	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-core_2.12\jars\sjson-new-core_2.12-0.8.2.jar	SUCCESS	CreationTime: 27.1.2018 12.05.42, LastAccessTime: 27.1.2018 12.05.42, LastWriteTime: 13.12.2017 4.46.50, ChangeTime: 27.1.2018 12.05.43, FileAttributes: A
10.11.01,2206268	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\sjson-new-core_2.12\jars\sjson-new-core_2.12-0.8.2.jar	SUCCESS	
10.11.01,2208066	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\shaded-scalajson_2.12\jars\shaded-scalajson_2.12-1.0.0-M4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2209400	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\shaded-scalajson_2.12\jars\shaded-scalajson_2.12-1.0.0-M4.jar	SUCCESS	CreationTime: 11.11.2017 15.01.27, LastAccessTime: 11.11.2017 15.01.27, LastWriteTime: 13.7.2017 0.28.14, ChangeTime: 11.11.2017 15.01.27, FileAttributes: A
10.11.01,2209809	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\com.eed3si9n\shaded-scalajson_2.12\jars\shaded-scalajson_2.12-1.0.0-M4.jar	SUCCESS	
10.11.01,2211402	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.spire-math\jawn-parser_2.12\jars\jawn-parser_2.12-0.10.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2212566	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.spire-math\jawn-parser_2.12\jars\jawn-parser_2.12-0.10.4.jar	SUCCESS	CreationTime: 1.8.2017 19.59.00, LastAccessTime: 1.8.2017 19.59.00, LastWriteTime: 13.11.2016 7.00.15, ChangeTime: 1.8.2017 19.59.00, FileAttributes: A
10.11.01,2212985	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.spire-math\jawn-parser_2.12\jars\jawn-parser_2.12-0.10.4.jar	SUCCESS	
10.11.01,2214808	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-position_2.12\jars\util-position_2.12-1.1.3.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2217237	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-position_2.12\jars\util-position_2.12-1.1.3.jar	SUCCESS	CreationTime: 23.4.2018 21.08.51, LastAccessTime: 23.4.2018 21.08.51, LastWriteTime: 19.3.2018 21.24.07, ChangeTime: 23.4.2018 21.08.51, FileAttributes: A
10.11.01,2218266	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-position_2.12\jars\util-position_2.12-1.1.3.jar	SUCCESS	
10.11.01,2220913	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-relation_2.12\jars\util-relation_2.12-1.1.3.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2222689	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-relation_2.12\jars\util-relation_2.12-1.1.3.jar	SUCCESS	CreationTime: 23.4.2018 21.08.51, LastAccessTime: 23.4.2018 21.08.51, LastWriteTime: 19.3.2018 21.24.09, ChangeTime: 23.4.2018 21.08.51, FileAttributes: A
10.11.01,2223444	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-relation_2.12\jars\util-relation_2.12-1.1.3.jar	SUCCESS	
10.11.01,2225796	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\actions_2.12\jars\actions_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2231281	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\actions_2.12\jars\actions_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.36, LastAccessTime: 23.4.2018 22.19.36, LastWriteTime: 9.4.2018 20.53.20, ChangeTime: 23.4.2018 22.19.36, FileAttributes: A
10.11.01,2232057	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\actions_2.12\jars\actions_2.12-1.1.4.jar	SUCCESS	
10.11.01,2234512	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\completion_2.12\jars\completion_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2236448	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\completion_2.12\jars\completion_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.39, LastAccessTime: 23.4.2018 22.19.39, LastWriteTime: 9.4.2018 20.53.02, ChangeTime: 23.4.2018 22.19.39, FileAttributes: A
10.11.01,2237105	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\completion_2.12\jars\completion_2.12-1.1.4.jar	SUCCESS	
10.11.01,2239300	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\jline\jline\jars\jline-2.14.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2241160	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\jline\jline\jars\jline-2.14.4.jar	SUCCESS	CreationTime: 30.7.2017 22.50.13, LastAccessTime: 30.7.2017 22.50.13, LastWriteTime: 6.6.2017 9.37.34, ChangeTime: 30.7.2017 22.50.13, FileAttributes: A
10.11.01,2241900	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\jline\jline\jars\jline-2.14.4.jar	SUCCESS	
10.11.01,2244157	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\io_2.12\jars\io_2.12-1.1.6.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2245988	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\io_2.12\jars\io_2.12-1.1.6.jar	SUCCESS	CreationTime: 23.4.2018 22.19.38, LastAccessTime: 23.4.2018 22.19.38, LastWriteTime: 6.4.2018 21.18.13, ChangeTime: 23.4.2018 22.19.38, FileAttributes: A
10.11.01,2246652	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\io_2.12\jars\io_2.12-1.1.6.jar	SUCCESS	
10.11.01,2248785	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\com.swoval\apple-file-events\jars\apple-file-events-1.3.0.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2250882	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\com.swoval\apple-file-events\jars\apple-file-events-1.3.0.jar	SUCCESS	CreationTime: 23.4.2018 22.19.41, LastAccessTime: 23.4.2018 22.19.41, LastWriteTime: 28.3.2018 21.15.14, ChangeTime: 23.4.2018 22.19.41, FileAttributes: A
10.11.01,2251772	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\com.swoval\apple-file-events\jars\apple-file-events-1.3.0.jar	SUCCESS	
10.11.01,2254036	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.5.0.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2255779	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.5.0.jar	SUCCESS	CreationTime: 27.1.2018 12.05.45, LastAccessTime: 27.1.2018 12.05.45, LastWriteTime: 13.9.2017 23.27.50, ChangeTime: 27.1.2018 12.05.47, FileAttributes: A
10.11.01,2256396	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna\jars\jna-4.5.0.jar	SUCCESS	
10.11.01,2258412	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna-platform\jars\jna-platform-4.5.0.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2260061	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna-platform\jars\jna-platform-4.5.0.jar	SUCCESS	CreationTime: 27.1.2018 12.05.47, LastAccessTime: 27.1.2018 12.05.47, LastWriteTime: 13.9.2017 23.29.49, ChangeTime: 27.1.2018 12.05.48, FileAttributes: A
10.11.01,2260597	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\net.java.dev.jna\jna-platform\jars\jna-platform-4.5.0.jar	SUCCESS	
10.11.01,2262854	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-control_2.12\jars\util-control_2.12-1.1.3.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2264203	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-control_2.12\jars\util-control_2.12-1.1.3.jar	SUCCESS	CreationTime: 23.4.2018 21.08.53, LastAccessTime: 23.4.2018 21.08.53, LastWriteTime: 19.3.2018 21.23.56, ChangeTime: 23.4.2018 21.08.53, FileAttributes: A
10.11.01,2264681	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-control_2.12\jars\util-control_2.12-1.1.3.jar	SUCCESS	
10.11.01,2266256	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\run_2.12\jars\run_2.12-1.1.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2267336	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\run_2.12\jars\run_2.12-1.1.4.jar	SUCCESS	CreationTime: 23.4.2018 22.19.37, LastAccessTime: 23.4.2018 22.19.37, LastWriteTime: 9.4.2018 20.52.53, ChangeTime: 23.4.2018 22.19.37, FileAttributes: A
10.11.01,2267759	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\run_2.12\jars\run_2.12-1.1.4.jar	SUCCESS	
10.11.01,2269316	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-logging_2.12\jars\util-logging_2.12-1.1.3.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2270487	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-logging_2.12\jars\util-logging_2.12-1.1.3.jar	SUCCESS	CreationTime: 23.4.2018 21.08.49, LastAccessTime: 23.4.2018 21.08.49, LastWriteTime: 19.3.2018 21.23.58, ChangeTime: 23.4.2018 21.08.49, FileAttributes: A
10.11.01,2270910	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-logging_2.12\jars\util-logging_2.12-1.1.3.jar	SUCCESS	
10.11.01,2272394	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.1.3.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2273400	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.1.3.jar	SUCCESS	CreationTime: 23.4.2018 21.08.53, LastAccessTime: 23.4.2018 21.08.53, LastWriteTime: 19.3.2018 21.23.57, ChangeTime: 23.4.2018 21.08.53, FileAttributes: A
10.11.01,2273849	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\util-interface\jars\util-interface-1.1.3.jar	SUCCESS	
10.11.01,2275778	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-api\jars\log4j-api-2.8.1.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2276909	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-api\jars\log4j-api-2.8.1.jar	SUCCESS	CreationTime: 11.11.2017 15.01.21, LastAccessTime: 11.11.2017 15.01.21, LastWriteTime: 27.2.2017 2.54.07, ChangeTime: 11.11.2017 15.01.22, FileAttributes: A
10.11.01,2277324	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-api\jars\log4j-api-2.8.1.jar	SUCCESS	
10.11.01,2278922	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-core\jars\log4j-core-2.8.1.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2279965	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-core\jars\log4j-core-2.8.1.jar	SUCCESS	CreationTime: 11.11.2017 15.01.22, LastAccessTime: 11.11.2017 15.01.22, LastWriteTime: 27.2.2017 3.11.22, ChangeTime: 11.11.2017 15.01.23, FileAttributes: A
10.11.01,2280355	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.apache.logging.log4j\log4j-core\jars\log4j-core-2.8.1.jar	SUCCESS	
10.11.01,2282029	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\com.lmax\disruptor\jars\disruptor-3.3.6.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2283476	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\com.lmax\disruptor\jars\disruptor-3.3.6.jar	SUCCESS	CreationTime: 11.11.2017 15.01.30, LastAccessTime: 11.11.2017 15.01.30, LastWriteTime: 3.10.2016 23.47.55, ChangeTime: 11.11.2017 15.01.30, FileAttributes: A
10.11.01,2284319	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\com.lmax\disruptor\jars\disruptor-3.3.6.jar	SUCCESS	
10.11.01,2286944	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.12.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2288764	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.12.4.jar	SUCCESS	CreationTime: 2.11.2017 14.04.34, LastAccessTime: 2.11.2017 14.04.34, LastWriteTime: 11.10.2017 10.15.40, ChangeTime: 2.11.2017 14.04.36, FileAttributes: A
10.11.01,2289472	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.12.4.jar	SUCCESS	
10.11.01,2291525	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\zinc-classpath_2.12\jars\zinc-classpath_2.12-1.1.5.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2293220	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\zinc-classpath_2.12\jars\zinc-classpath_2.12-1.1.5.jar	SUCCESS	CreationTime: 23.4.2018 22.19.40, LastAccessTime: 23.4.2018 22.19.40, LastWriteTime: 9.4.2018 19.09.15, ChangeTime: 23.4.2018 22.19.40, FileAttributes: A
10.11.01,2293902	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-sbt\zinc-classpath_2.12\jars\zinc-classpath_2.12-1.1.5.jar	SUCCESS	
10.11.01,2295988	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-compiler\jars\scala-compiler-2.12.4.jar	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened
10.11.01,2298362	java.exe	20648	QueryBasicInformationFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-compiler\jars\scala-compiler-2.12.4.jar	SUCCESS	CreationTime: 2.11.2017 14.04.28, LastAccessTime: 2.11.2017 14.04.28, LastWriteTime: 11.10.2017 10.45.52, ChangeTime: 2.11.2017 14.04.34, FileAttributes: A
10.11.01,2298851	java.exe	20648	CloseFile	C:\Users\oc\.ivy2\cache\org.scala-lang\scala-compiler\jars\scala-compiler-2.12.4.jar	SUCCESS	
10.11.01,2300532	java.exe	20648	CreateFile	C:\Users\oc\.ivy2\cache\org.scala-lang.modules\scala-xml_2.12\bundles\scala-xml_2.12-1.0.6.jar	SHARING VIOLATION	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: Read, AllocationSize: n/a
```

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/io/pull/134
