### ISSUE TITLE
False evicted warning for versions intervals

### ISSUE THREAD

**Issue by BITespresso** [sbt/sbt#6244]
## steps

Using sbt 1.4.6 or 1.3.13 I do get a false evicted warning for a library which uses a version interval.

1. Run `sbt` in a terminal
2. Execute `evicted`

## problem

I get an evicted warning for this library:

```
[warn]  * net.minidev:json-smart:2.3 is selected over {[1.3.1,2.3], [1.3.1,2.3]}
[warn]      +- com.nimbusds:oauth2-oidc-sdk:8.22                  (depends on [1.3.1,2.3])
[warn]      +- com.nimbusds:nimbus-jose-jwt:8.20.1                (depends on [1.3.1,2.3])
```

## expectation

Do not treat this situation as an evicted warning, because selecting version 2.3 is a valid option when both libraries that require `net.minidev:json-smart` allow version `2.3` in a version interval `(depends on [1.3.1,2.3])`

## notes

This is probably an error in `sbt/librarymanagement` that is affecting a lot of sbt versions.

**Comment by eed3si9n** [comment]
@BITespresso Thanks for the report!

Do you have a publicly reproducible build.sbt so we can use it as a test?

**Comment by BITespresso** [comment]
The project where the issue occured is not public, but I have put a demo project together which you can use as an example for this issue: https://github.com/BITespresso/sbt-evicted-demo

Just clone this and execute `sbt` in a shell followed by the sbt command `evicted`.

**Comment by BITespresso** [comment]
I created a pull request which should fix this issue: https://github.com/sbt/librarymanagement/pull/362

**Comment by Eruis2579** [comment]
Hi, @eed3si9n  This issue was solved? If not, can I try this?

**Comment by eed3si9n** [comment]
@Eruis2579 I think this one is still open. Before working on fixes please follow the repro project provided by the OP and see this problem still exists on a freshly baked sbt 2.x. My guess is that we can still reproduce this since I added the help-wanted tag 3 weeks ago.

**Comment by Eruis2579** [comment]
<img width="758" height="368" alt="Image" src="https://github.com/user-attachments/assets/f5c13f34-6ad4-40dd-9920-11ae860a056b" />

I confirmed this problem still exists. Can I try this?

**Comment by eed3si9n** [comment]
@Eruis2579 Yes, plz go ahead. Thanks for the confirmation.

**Comment by Eruis2579** [comment]
Hi, @eed3si9n , I have fixed this issue and add test for updates. Please review. Thanks
