### ISSUE TITLE
version-specific documentation search is a lie

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#829]
When you change the version of documentation you're looking at, the search box magically changes, saying things like "Search 0.12.1 on Google" or "Search 0.13.0 on Google". Truly we are living in the future! But then it issues the same search every time.

``` html
<div class="search-box">
  <form method="get" action="http://www.google.com/search" id="search">
    <input type="search" placeholder="Search 0.13.0 on Google" name="q" results="10" size="29" id="search-input">
    <input type="hidden"  name="sitesearch" value="http://www.scala-sbt.org/release/docs/"> 
    <input type="submit" id="submit-search">
  </form>
</div>
```

That is a lot worse than no magic. It was quite a while before I noticed the reason there was no indexed documentation available for some things is that it was never even looking for it. For instance, if it had really issued this search
`export site:http://www.scala-sbt.org/0.13.0/docs/`
like it claims it did, I'd be looking at http://www.scala-sbt.org/0.13.0/docs/Community/ChangeSummary_0.13.0.html. In reality it only comes up with a useless red herring.

**Comment by harrah** [comment]
Fixed, thanks!

**Comment by harrah** [comment]
Oh, and I'll push the updated docs later.

**Comment by SethTisue** [comment]
this came up on IRC just now. did it slip your mind?

**Comment by OlegYch** [comment]
there is still a problem with version specific search
e.g. https://www.google.com/search?q=sbt%20using%20plugins shows 'Using Plugins' page
but https://www.google.com/search?q=using+plugins&sitesearch=http%3A%2F%2Fwww.scala-sbt.org%2F0.13.1%2Fdocs%2F (from search box in scala-sbt.org) does not show it
perhaps google filters out duplicate results (ie coming from release/ and 0.13.1/ ) ?
