### ISSUE TITLE
scripted tests that have an invalid build file hang on windows when running sbt scripted

### ISSUE THREAD

**Issue by pfn** [sbt/sbt#853]
Created a scripted test that has an invalid build file then run sbt scripted on windows; it results in a hang (test environment = windows7 +  console2 + git-bash + win-sbt.sh)

**Comment by pfn** [comment]
When I set `scriptedBufferLog := false` this is the last thing I see:

```
[error] C:\Users\pfnguyen\AppData\Local\Temp\sbt_ea43318c\hello-world-scala-gradle-layout\build.sbt:14: error: value ! is not a member of Seq[java.lang.Comparable[_ >: java.io.File with java.lang.String <: java.lang.Comparable[_ >: java.io.File with java.lang.String <: java.io.Serializable] with java.io.Serializable] with java.io.Serializable]
[error]   Seq(dexdump.getAbsolutePath, layout.bin / "classes.dex") !
[error]                                                            ^
[info] [error] Type error in expression
```

**Comment by harrah** [comment]
This commit reworked handling of failed build definitions: 6755f2595b6dab5a586eea742c69bac2741866fd.  So, it might fix the problem as a side effect, but your problem might be a jline thing or something else.  (I haven't tried to reproduce yet, so I'm just commenting here in case it is fixed by this.)

**Comment by eed3si9n** [comment]
Does this still happen with 0.13.1 or 0.13.2-RC1?

**Comment by pfn** [comment]
This still occurs on 0.13.5

```
[info] [warn] there were 1 feature warning(s); re-run with -feature for details [info] [warn] one warning found
[error] C:\Users\pfnguyen\AppData\Local\Temp\sbt_6d87d8b8\lib-with-resources\build.sbt:7: error: reference to platformTarget is ambiguous;
[error] it is imported twice in the same scope by
[error] import android.Keys._
[info] [error] Type error in expression
[error] and import _root_.android.AndroidPlugin.autoImport._
[error] platformTarget in Android := "android-17"
[error] ^
```

I get this error while running a scripted test and it all stops there

**Comment by pfn** [comment]
Still hangs:

```
[info] [info] Compiling 1 Scala source to C:\Users\pfnguyen\AppData\Local\Temp\sbt_816dd178\proguard-cache-duplicate-classes\project\target\scala-2.10\sbt-0.13\classes...
[error] C:\Users\pfnguyen\AppData\Local\Temp\sbt_816dd178\proguard-cache-duplicate-classes\tests.sbt:3: error: not found: value builder
[error] TaskKey[Unit]("check-dex") <<= ( builder in Android
[error]                                  ^
[info] [error] Type error in expression
```

Unbuffered output, process just stops there.

**Comment by pfn** [comment]
A recent update:

Whenever my scripted tests hang, I press q and enter, it appears it just sits there waiting for input without showing the prompt. Pressing `q` and `enter` tells the hung test to quit...

**Comment by eed3si9n** [comment]
I am closing this due to inactivity.
